### ISSUE TITLE
main.dart should be renamed to server.dart.

### ISSUE THREAD

**Issue by runarj** [shamblett/cloudruntest#1]
I am not entirely sure, but when I tested this today it failed. Correction was simple; just rename main.dart to server.dart.

**Comment by shamblett** [comment]
I've just run this using googles cloud shell with no problems, output below 

stevehamblett@cloudshell:~/repositories/dart/cloudruntest (warm-actor-356)$ gcloud beta builds submit --tag gcr.io/warm-actor-356/helloworld
Creating temporary tarball archive of 6 file(s) totalling 39.8 KiB before compression.
Some files were not included in the source upload.

Check the gcloud log [/tmp/tmp.2Nl6SWngPN/logs/2019.08.01/08.21.26.083147.log] to see which files and the contents of the
default gcloudignore file used (see `$ gcloud topic gcloudignore` to learn
more).

Uploading tarball of [.] to [gs://warm-actor-356_cloudbuild/source/1564644086.98-28c7542678924369932727a2b7a84434.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/warm-actor-356/builds/64bcda7f-3b36-4449-af89-18e28cce08ca].
Logs are available at [https://console.cloud.google.com/gcr/builds/64bcda7f-3b36-4449-af89-18e28cce08ca?project=245662613464].
--------------------------------------------------------------------------------------------------------------- REMOTE BUILD OUTPUT ----------------------------------------------------------------------------------------------------------------
starting build "64bcda7f-3b36-4449-af89-18e28cce08ca"

FETCHSOURCE
Fetching storage object: gs://warm-actor-356_cloudbuild/source/1564644086.98-28c7542678924369932727a2b7a84434.tgz#1564644088020109
Copying gs://warm-actor-356_cloudbuild/source/1564644086.98-28c7542678924369932727a2b7a84434.tgz#1564644088020109...
/ [1 files][ 14.5 KiB/ 14.5 KiB]
Operation completed over 1 objects/14.5 KiB.
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon   47.1kB
Step 1/3 : FROM google/dart-runtime
latest: Pulling from google/dart-runtime
68ca0147cee7: Pulling fs layer
bd441962200f: Pulling fs layer
cb5e2a2d56c2: Pulling fs layer
c103d6ef5b79: Pulling fs layer
bfa83e4ada8a: Pulling fs layer
c103d6ef5b79: Waiting
bfa83e4ada8a: Waiting
cb5e2a2d56c2: Verifying Checksum
cb5e2a2d56c2: Download complete
68ca0147cee7: Verifying Checksum
68ca0147cee7: Download complete
c103d6ef5b79: Verifying Checksum
c103d6ef5b79: Download complete
bfa83e4ada8a: Verifying Checksum
bfa83e4ada8a: Download complete
bd441962200f: Verifying Checksum
bd441962200f: Download complete
68ca0147cee7: Pull complete
bd441962200f: Pull complete
cb5e2a2d56c2: Pull complete
c103d6ef5b79: Pull complete
bfa83e4ada8a: Pull complete
Digest: sha256:c292c58964e68243a2b6bbe67f88e329f566ea5af45e8ad1e4ea6280fbd8c5fe
Status: Downloaded newer image for google/dart-runtime:latest
# Executing 4 build triggers
 ---> Running in 8fe5c32b948f
Resolving dependencies...  < snip>
Removing intermediate container 8fe5c32b948f
 ---> Running in 934f0b8cb5ca
Resolving dependencies...
Got dependencies!
Removing intermediate container 934f0b8cb5ca
 ---> b7af72b2d58e
Step 2/3 : ENV PORT 8080
 ---> Running in 7d020a9f9953
Removing intermediate container 7d020a9f9953
 ---> 378c976f0235
Step 3/3 : ENV TARGET "World + Dog"
 ---> Running in 00321b410418
Removing intermediate container 00321b410418
 ---> aaaa3fbb0a9e
Successfully built aaaa3fbb0a9e
Successfully tagged gcr.io/warm-actor-356/helloworld:latest
PUSH
Pushing gcr.io/warm-actor-356/helloworld
The push refers to repository [gcr.io/warm-actor-356/helloworld]
7f94ac724d36: Preparing
9ab09fb32107: Preparing
f4f9f2278b4f: Preparing
a21311e008c8: Preparing
f1a3e706bfeb: Preparing
357b88e3ddef: Preparing
d47bca54470c: Preparing
b8c384805173: Preparing
e3f217e75d05: Preparing
357b88e3ddef: Waiting
d47bca54470c: Waiting
b8c384805173: Waiting
e3f217e75d05: Waiting
f1a3e706bfeb: Pushed
a21311e008c8: Pushed
f4f9f2278b4f: Pushed
7f94ac724d36: Pushed
9ab09fb32107: Pushed
357b88e3ddef: Pushed
d47bca54470c: Pushed
e3f217e75d05: Pushed
b8c384805173: Pushed
latest: digest: sha256:494fcae82af2d5a5b5a3a1290ae664da42646359db4c30f34059efaede0a28b9 size: 2196
DONE
----------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------

ID                                    CREATE_TIME                DURATION  SOURCE                                                                                    IMAGES                                      STATUS
64bcda7f-3b36-4449-af89-18e28cce08ca  2019-08-01T07:21:28+00:00  1M41S     gs://warm-actor-356_cloudbuild/source/1564644086.98-28c7542678924369932727a2b7a84434.tgz  gcr.io/warm-actor-356/helloworld (+1 more)  SUCCESS

stevehamblett@cloudshell:~/repositories/dart/cloudruntest (warm-actor-356)$ gcloud beta run deploy --image gcr.io/warm-actor-356/helloworld
Please choose a target platform:
 [1] gke
 [2] managed
 [3] cancel
Please enter your numeric choice:  2

To specify the platform yourself, pass `--platform managed`. Or, to make this the default target platform, run `gcloud config set run/platform managed`.

Please specify a region:
 [1] asia-northeast1
 [2] europe-west1
 [3] us-central1
 [4] us-east1
 [5] cancel
Please enter your numeric choice:  2

To make this the default region, run `gcloud config set run/region europe-west1`.

Service name (helloworld):
Allow unauthenticated invocations to [helloworld] (y/N)?  y

Deploying container to Cloud Run service [helloworld] in project [warm-actor-356] region [europe-west1]
✓ Deploying new service... Done.                                       
  ✓ Creating Revision...                    
  ✓ Routing traffic...
  ✓ Setting IAM Policy...
Done.
Service [helloworld] revision [helloworld-00001] has been deployed and is serving traffic at https://helloworld-aitq74pqtq-ew.a.run.app
stevehamblett@cloudshell:~/repositories/dart/cloudruntest (warm-actor-356)$

The output of the url is the usual 

Hello World + Dog

How did you test it?

**Comment by runarj** [comment]
I am running on macOS, with an updated Google Cloud SDK. In the Cloud Run console i get:

2019-08-03 23:14:49.485 CESTObservatory listening on http://0.0.0.0:8181/XQGUqNCkjhU=/
2019-08-03 23:14:51.052 CESTContainer called exit(254).
2019-08-03 23:14:51.052 CESTError: Error when reading '**bin/server.dart**': No such file or directory

That error message helped me fix the problem. Below is the output in the terminal:

RunarsMacBookPro:server runarjordahl$ builds submit --tag gcr.io/epigent-abcdefg/helloworld
-bash: builds: command not found
RunarsMacBookPro:server runarjordahl$ gcloud beta builds submit --tag gcr.io/epigent-abcdefg/helloworld
Creating temporary tarball archive of 6 file(s) totalling 10.4 KiB before compression.
Uploading tarball of [.] to [gs://epigent-abcdefg_cloudbuild/source/1564866361.86-42fc04092ee24bb0bb1119f646930501.tgz]
Created [https://cloudbuild.googleapis.com/v1/projects/epigent-abcdefg/builds/4c24a0fa-3ebd-4268-9329-0db18a2c1be1].
Logs are available at [https://console.cloud.google.com/gcr/builds/4c24a0fa-3ebd-4268-9329-0db18a2c1be1?project=5791779101].
------------------------------------ REMOTE BUILD OUTPUT ------------------------------------
starting build "4c24a0fa-3ebd-4268-9329-0db18a2c1be1"

FETCHSOURCE
Fetching storage object: gs://epigent-abcdefg_cloudbuild/source/1564866361.86-42fc04092ee24bb0bb1119f646930501.tgz#1564866362970182
Copying gs://epigent-abcdefg_cloudbuild/source/1564866361.86-42fc04092ee24bb0bb1119f646930501.tgz#1564866362970182...
/ [1 files][  1.7 KiB/  1.7 KiB]
Operation completed over 1 objects/1.7 KiB.
BUILD
Already have image (with digest): gcr.io/cloud-builders/docker
Sending build context to Docker daemon  17.41kB
Step 1/3 : FROM google/dart-runtime
latest: Pulling from google/dart-runtime
68ca0147cee7: Pulling fs layer
bd441962200f: Pulling fs layer
cb5e2a2d56c2: Pulling fs layer
c103d6ef5b79: Pulling fs layer
bfa83e4ada8a: Pulling fs layer
c103d6ef5b79: Waiting
bfa83e4ada8a: Waiting
cb5e2a2d56c2: Verifying Checksum
cb5e2a2d56c2: Download complete
68ca0147cee7: Verifying Checksum
68ca0147cee7: Download complete
c103d6ef5b79: Verifying Checksum
c103d6ef5b79: Download complete
bfa83e4ada8a: Verifying Checksum
bfa83e4ada8a: Download complete
bd441962200f: Verifying Checksum
bd441962200f: Download complete
68ca0147cee7: Pull complete
bd441962200f: Pull complete
cb5e2a2d56c2: Pull complete
c103d6ef5b79: Pull complete
bfa83e4ada8a: Pull complete
Digest: sha256:c292c58964e68243a2b6bbe67f88e329f566ea5af45e8ad1e4ea6280fbd8c5fe
Status: Downloaded newer image for google/dart-runtime:latest
# Executing 4 build triggers
 ---> Running in c4ec25fd068d
Resolving dependencies...
Downloading shelf 0.7.5...
Downloading path 1.6.4...
Downloading collection 1.14.11...
Downloading stream_channel 2.0.0...
Downloading async 2.3.0...
Downloading stack_trace 1.9.3...
Downloading http_parser 3.1.3...
Downloading typed_data 1.1.6...
Downloading string_scanner 1.0.4...
Downloading source_span 1.5.5...
Downloading charcode 1.1.2...
Downloading meta 1.1.7...
Downloading term_glyph 1.1.0...
Got dependencies!
Removing intermediate container c4ec25fd068d
 ---> Running in 8bb9de970f03
Resolving dependencies...
Got dependencies!
Removing intermediate container 8bb9de970f03
 ---> d4e7d367eaca
Step 2/3 : ENV PORT 8080
 ---> Running in 87cd0ef5ab82
Removing intermediate container 87cd0ef5ab82
 ---> 333c06262027
Step 3/3 : ENV TARGET "World + Dog"
 ---> Running in e781f77698c7
Removing intermediate container e781f77698c7
 ---> 88b4d7649e4a
Successfully built 88b4d7649e4a
Successfully tagged gcr.io/epigent-abcdefg/helloworld:latest
PUSH
Pushing gcr.io/epigent-abcdefg/helloworld
The push refers to repository [gcr.io/epigent-abcdefg/helloworld]
3f0edeb97f74: Preparing
c92f33e50b49: Preparing
f4b4ca78e7cc: Preparing
7b710be8a5e7: Preparing
f1a3e706bfeb: Preparing
357b88e3ddef: Preparing
d47bca54470c: Preparing
b8c384805173: Preparing
e3f217e75d05: Preparing
357b88e3ddef: Waiting
d47bca54470c: Waiting
b8c384805173: Waiting
e3f217e75d05: Waiting
f1a3e706bfeb: Layer already exists
357b88e3ddef: Layer already exists
d47bca54470c: Layer already exists
b8c384805173: Layer already exists
e3f217e75d05: Layer already exists
c92f33e50b49: Pushed
7b710be8a5e7: Pushed
f4b4ca78e7cc: Pushed
3f0edeb97f74: Pushed
latest: digest: sha256:3d2a9b842074271d7681bf4bf4860fa18b1ea0ded681750893ab6fab5d9944e1 size: 2195
DONE
---------------------------------------------------------------------------------------------

ID                                    CREATE_TIME                DURATION  SOURCE                                                                                     IMAGES                                       STATUS
4c24a0fa-3ebd-4268-9329-0db18a2c1be1  2019-08-03T21:06:04+00:00  48S       gs://epigent-abcdefg_cloudbuild/source/1564866361.86-42fc04092ee24bb0bb1119f646930501.tgz  gcr.io/epigent-abcdefg/helloworld (+1 more)  SUCCESS
RunarsMacBookPro:server runarjordahl$ gcloud beta run deploy --image gcr.io/epigent-abcdefg/helloworld
Please choose a target platform:
 [1] gke
 [2] managed
 [3] cancel
Please enter your numeric choice:  2

To specify the platform yourself, pass `--platform managed`. Or, to make this the default target platform, run `gcloud config set run/platform managed`.

Please specify a region:
 [1] asia-northeast1
 [2] europe-west1
 [3] us-central1
 [4] us-east1
 [5] cancel
Please enter your numeric choice:  3

To make this the default region, run `gcloud config set run/region us-central1`.

Service name (helloworld):
Deploying container to Cloud Run service [helloworld] in project [epigent-abcdefg] region [us-central1]
X Deploying... Cloud Run error: Container failed to start. Failed to start and then listen o
n the port defined by the PORT environment variable. Logs for this revision might contain mo
re information.
  X Creating Revision... Cloud Run error: Container failed to start. Failed to start and the
  n listen on the port defined by the PORT environment variable. Logs for this revision migh
  t contain more information.
  . Routing traffic...
Deployment failed
ERROR: (gcloud.beta.run.deploy) Cloud Run error: Container failed to start. Failed to start and then listen on the port defined by the PORT environment variable. Logs for this revision might contain more information.
RunarsMacBookPro:server runarjordahl$

**Comment by shamblett** [comment]
Just looking for the first diff, 

I get 

Creating temporary tarball archive of 6 file(s) totalling 39.8 KiB before compression.
Some files were not included in the source upload...

You get 

Creating temporary tarball archive of 6 file(s) totalling 10.4 KiB before compression.

The size is different, could you try just pulling the repo and running straight from it

**Comment by runarj** [comment]
I might have found the source of the problem: I did not pull the code. Instead I simply followed the steps in the README.md file. There, step 3 says "Create a new file bin/main.dart", while the actual code does have a bin/server.dart file.

Should the README.md be updated with info that the file should be named server.dart?

Anyways... This is just details. Thanks for providing the example!

**Comment by shamblett** [comment]
Yes, well spotted, updated this

**Comment by runarj** [comment]
Also, the contents in README.md and the actual server.dart file is a bit different. I do not know whether it is relevant, but server.dart says

Future main() async {

while the README.md says

void main() {

**Comment by shamblett** [comment]
Yes, they should be the same, updated
